# Generated by Django 2.2.11 on 2023-01-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=16)),
                ('topic', models.CharField(max_length=32)),
                ('channel_title', models.CharField(max_length=32)),
                ('video_title', models.CharField(max_length=128)),
                ('comment_id', models.CharField(max_length=32)),
                ('comment_text', models.TextField()),
                ('tags', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
